GET http://localhost:9080/app/user
###
GET http://localhost:9080/app/user/1
###

GET http://localhost:9080/app/api/portrait/1
###

POST http://localhost:9080/app/api/portrait/4
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="portrait"; filename="avatar3.png'

< ../../src/main/resources/avatar3.png
--boundary--
###

PUT http://localhost:9080/app/api/portrait/4
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="portrait"; filename="avatar2.png'

< ../../src/main/resources/avatar2.png
--boundary--
###
DELETE http://localhost:9080/app/api/portrait/4
###

GET http://localhost:9080/app/api/dishes
###

GET http://localhost:9080/app/api/dishes/1
###

DELETE http://localhost:9080/app/api/dishes/2
###

POST http://localhost:9080/app/api/dishes
Content-Type: application/json

{
  "name": "jablecznik",
  "isVegan": false,
  "price": 10.00
}
###

PUT http://localhost:9080/app/api/dishes/9
Content-Type: application/json

{
  "name": "szarlotka",
  "isVegan": false,
  "price": 20.00
}
###

GET http://localhost:9080/app/api/dishes/1/opinions
###

GET http://localhost:9080/app/api/dishes/1/opinions/5
###

DELETE http://localhost:9080/app/api/dishes/1/opinions/5
###

POST http://localhost:9080/app/api/dishes/1/opinions
Content-Type: application/json

{
  "userId": 1,
  "content": "good"
}
###


PUT http://localhost:9080/app/api/dishes/1/opinions/9
Content-Type: application/json

{
  "userId": 1,
  "content": "very good"
}
###







