GET http://localhost:9080/app/user
###
GET http://localhost:9080/app/user/1
###

GET http://localhost:9080/app/api/portrait/1
###

POST http://localhost:9080/app/api/portrait/4
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="portrait"; filename="avatar3.png'

< ../../src/main/resources/avatar3.png
--boundary--
###

PUT http://localhost:9080/app/api/portrait/4
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="portrait"; filename="avatar2.png'

< ../../src/main/resources/avatar2.png
--boundary--
###
DELETE http://localhost:9080/app/api/portrait/4
###

GET http://localhost:9080/app/api/dishes
###

GET http://localhost:9080/app/api/dishes/1
###

DELETE http://localhost:9080/app/api/dishes/2
###

POST http://localhost:9080/app/api/dishes
Content-Type: application/json

{
  "name": "jablecznik",
  "isVegan": false,
  "price": 10.00
}
###

PUT http://localhost:9080/app/api/dishes/9
Content-Type: application/json

{
  "name": "szarlotka",
  "isVegan": false,
  "price": 20.00
}
###

GET http://localhost:9080/app/api/dishes/1/opinions
###

GET http://localhost:9080/app/api/dishes/1/opinions/5
###

DELETE http://localhost:9080/app/api/dishes/1/opinions/5
###

POST http://localhost:9080/app/api/dishes/1/opinions
Content-Type: application/json

{
  "userId": 1,
  "content": "good"
}
###

PUT http://localhost:9080/app/api/dishes/1/opinions/9
Content-Type: application/json

{
  "userId": 1,
  "content": "very good"
}
###





### dXNlcjE6YWJj - user / YWRtaW46YWRtaW4= - admin / bmV3OmFiYw== - new user
// @no-cookie-jar
POST http://localhost:9080/app/api/users
Content-Type: application/json

{
  "userName": "new",
  "password": "abc",
  "email": "new@gmail.com",
  "birthDate": "2000-01-01"
}
###


// @no-cookie-jar
GET http://localhost:9080/app/user
Authorization: Basic bmV3OmFiYw==
###

// @no-cookie-jar
GET http://localhost:9080/app/user
Authorization: Basic YWRtaW46YWRtaW4=
###

// @no-cookie-jar
GET http://localhost:9080/app/api/dishes
Authorization: Basic bmV3OmFiYw==
###

// @no-cookie-jar
GET http://localhost:9080/app/api/dishes
Authorization: Basic YWRtaW46YWRtaW4=
###

// @no-cookie-jar
POST http://localhost:9080/app/api/dishes
Content-Type: application/json
Authorization: Basic bmV3OmFiYw==

{
  "name": "jablecznik",
  "isVegan": false,
  "price": 10.00
}
###

// @no-cookie-jar
POST http://localhost:9080/app/api/dishes
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "name": "jablecznik",
  "isVegan": false,
  "price": 10.00
}
###


// @no-cookie-jar
DELETE http://localhost:9080/app/api/dishes/2
Authorization: Basic bmV3OmFiYw==
###

// @no-cookie-jar
DELETE http://localhost:9080/app/api/dishes/2
Authorization: Basic YWRtaW46YWRtaW4=
###

// @no-cookie-jar
GET http://localhost:9080/app/api/dishes/1/opinions
Authorization: Basic bmV3OmFiYw==
###

// @no-cookie-jar
GET http://localhost:9080/app/api/dishes/1/opinions
Authorization: Basic YWRtaW46YWRtaW4=
###

POST http://localhost:9080/app/api/dishes/1/opinions
Content-Type: application/json
Authorization: Basic bmV3OmFiYw==

{
  "content": "good"
}
###

// @no-cookie-jar
PUT http://localhost:9080/app/api/dishes/1/opinions/8
Authorization: Basic bmV3OmFiYw==
Content-Type: application/json

{
  "content": "very good"
}
###

// @no-cookie-jar
PUT http://localhost:9080/app/api/dishes/1/opinions/8
Authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/json

{
  "content": "very good"
}
###

// @no-cookie-jar
PUT http://localhost:9080/app/api/dishes/1/opinions/11
Authorization: Basic bmV3OmFiYw==
Content-Type: application/json

{
"content": "very very good"
}
###

// @no-cookie-jar
DELETE http://localhost:9080/app/api/dishes/1/opinions/8
Authorization: Basic bmV3OmFiYw==
###

// @no-cookie-jar
DELETE http://localhost:9080/app/api/dishes/1/opinions/8
Authorization: Basic YWRtaW46YWRtaW4=
###

// @no-cookie-jar
DELETE http://localhost:9080/app/api/dishes/1/opinions/11
Authorization: Basic bmV3OmFiYw==
###
